Implement CheckV processing script
Added a script to run CheckV on phage samples using apptainer.

diff --git a/preprocessing/CheckV b/preprocessing/CheckV
--- a/preprocessing/CheckV
+++ b/preprocessing/CheckV
@@ -25,3 +25,38 @@ apptainer exec $CHECKV checkv end_to_end \
     /scratch/mogakwu/binf_6999_2026/practice/checkv_test \
     -d $CHECKVDB \
     -t 4
+
+#Load apptainer
+module load StdEnv/2023
+module load apptainer/1.4.5
+
+#Paths
+BASEDIR=/scratch/mogakwu/binf_6999_2026
+CHECKV=$BASEDIR/checkv.sif
+CHECKVDB=$BASEDIR/checkv_db/checkv-db-v1.2
+PHAGE_DIR=$BASEDIR/phages
+OUTDIR=$BASEDIR/checkv_results
+mkdir -p $OUTDIR
+
+#Get the sample for this array task
+FASTA=$(ls $PHAGE_DIR/*.fasta | sed -n "${SLURM_ARRAY_TASK_ID}p")
+SAMPLE=$(basename $FASTA .fasta)
+
+echo "[START] Running CheckV on $SAMPLE"
+
+#Run CheckV
+apptainer exec $CHECKV checkv end_to_end \
+    $FASTA \
+    $OUTDIR/${SAMPLE} \
+    -d $CHECKVDB \
+    -t 4
+
+#Check success
+if [[ $? -eq 0 ]]; then
+    echo "[SUCCESS] CheckV completed for $SAMPLE"
+else
+    echo "[ERROR] CheckV failed for $SAMPLE"
+    exit 1
+fi
+
+echo "[DONE] $SAMPLE finished"
